### PR TITLE
Use latest minitest

### PR DESCRIPTION
**Pull request by tubbo**
Loosens minitest version so this gem is compatible with Rails 5 apps.

Also, could we get a rubygems release?

### CODE REVIEW

**Comment by lauri** [comment]
Take a look at the minitest-5.5 branch, it has saner minitest requirements and some other fixes.

**Comment by tubbo** [comment]
Awesome, any chance of getting that merged into master @lauri? You could release 'master' as a v1 and 'minitest-5.5' as a v2 or something, that way parallel development can still happen but we can just install the gem from RubyGems.

**Comment by lauri** [comment]
Merged to master. I might release a gem later if I get on top of things. Right now I don't even know if this works with the latest Minitest.

**Comment by tubbo** [comment]
cool, thanks. i guess there's only one way to find out (well, 2...but you have no tests written)

**Pull request closed without merging**
